schema_version = "1.0.2"
id = "empty_crop_tool"
version = "1.0.2"
name = "Empty Image Crop"
tagline = "Recadrage pour Empty Image via pourcentages"
maintainer = "Kwyk"
type = "add-on"
# Changement pour une licence libre (GPL v3)
license = ["GPL-3.0-or-later"]
blender_version_min = "4.2.0"
